### ISSUE TITLE
Possible bug in api_doc_gen

### ISSUE THREAD

**Issue by digitaldavenyc** [hfaran/Tornado-JSON#78]
My first post for this project, so I will start by saying thank you for creating this extension to Tornado!

So when I add a schema to a POST request, receiving the error below. Seems there is an error trying to split on the schema to generate the docs. I would think it's better to show a warning error for something like this if there is an issue parsing a schema somewhere, doc generation should be able to fail gracefully IMO. 

```
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    main()
  File "main.py", line 14, in main
    application = Application(routes=routes, settings={})
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/application.py", line 22, in __init__
    api_doc_gen(routes)
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 249, in api_doc_gen
    documentation = get_api_docs(routes)
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 236, in get_api_docs
    documentation.append(_get_route_doc(url, rh))
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 209, in _get_route_doc
    rh_doc=_add_indent(_get_rh_doc(rh), 4)
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 188, in _get_rh_doc
    for method_name, method in _get_rh_methods(rh)])
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 188, in <listcomp>
    for method_name, method in _get_rh_methods(rh)])
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 179, in _get_method_doc
    notes=_get_notes(method),
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 162, in _get_notes
    _add_indent(inspect.getdoc(method), 4)
  File "/source/virtualenvs/grooveweb/lib/python3.4/site-packages/tornado_json/api_doc_gen.py", line 101, in _add_indent
    lines = string.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```

Here is a copy of the schema I used in the class in case it's helpful

```
@schema.validate(
        input_schema={
            "type": "object",
            "properties": {
                "location": {"type": "array"},
                "image": {"type": "string"}
            }
        },
        input_example={
            "location": [40.1, 71.1],
            "image": "http://imgr.com/blajsjdjs.jpg"
        },
        output_schema={
            "type": "object",
            "properties": {
                "message": {"type": "string"}
            }
        },
        output_example={
            "message": "Very Important Post-It Note was posted."
        },
    )
```

**Comment by hfaran** [comment]
Thanks for the bug report, @digitaldavenyc!

I have pushed a fix at #79; can you checkout the branch (`hfaran_get_notes`) and see if that fixes it for you?
