### ISSUE TITLE
auto route generation fails when supplied namespaced package

### ISSUE THREAD

**Issue by djbright** [hfaran/Tornado-JSON#96]
Firstly, thanks contributors for your good work!

Currently using tornado-json 1.2.2 with Python 3.5.2

The main issue is that [pyclbr currently doesn't support namespace packages](https://bugs.python.org/issue26584) and `get_routes` fails accordingly. Same app/handlers work fine with non-namespaced packages, but we are pretty invested in namespacing due to a relatively large project. As a result, we have reverted to manually specifying routes.

The traceback below details what we see when we attempt to use `get_routes`. The deployed tornado app (`nspkg.scg.app.tornado_app1`) imports the tornado-json handlers from the `nspkg.lib.tornado_app.api` package. 

```
Traceback (most recent call last):
  File "/usr/bin/tornado_app1", line 9, in <module>
    load_entry_point('nspkg.scg==1.0', 'console_scripts', 'tornado_app1')()
  File "/usr/lib/python3.5/site-packages/nspkg/scg/app/tornado_app1/tornado_app1.py", line 37, in main
  File "/usr/lib/python3.5/site-packages/nspkg/lib/tornado_app/tornado_app.py", line 951, in main
    fca_instance = tornado_app_application_type(**settings)
  File "/usr/lib/python3.5/site-packages/nspkg/lib/singleton.py", line 32, in __call__
  File "/usr/lib/python3.5/site-packages/nspkg/scg/app/tornado_app1/tornado_app1.py", line 24, in __init__
  File "/usr/lib/python3.5/site-packages/nspkg/lib/tornado_app/tornado_app.py", line 59, in __init__
    routes = get_routes(api)
  File "/usr/lib/python3.5/site-packages/tornado_json/routes.py", line 26, in get_routes
  File "/usr/lib/python3.5/site-packages/tornado_json/routes.py", line 25, in <listcomp>
  File "/usr/lib/python3.5/site-packages/tornado_json/routes.py", line 156, in get_module_routes
  File "/usr/lib/python3.5/pyclbr.py", line 85, in readmodule
    for key, value in _readmodule(module, path or []).items():
  File "/usr/lib/python3.5/pyclbr.py", line 130, in _readmodule
    parent = _readmodule(package, path, inpackage)
  File "/usr/lib/python3.5/pyclbr.py", line 130, in _readmodule
    parent = _readmodule(package, path, inpackage)
  File "/usr/lib/python3.5/pyclbr.py", line 130, in _readmodule
    parent = _readmodule(package, path, inpackage)
  File "/usr/lib/python3.5/pyclbr.py", line 130, in _readmodule
    parent = _readmodule(package, path, inpackage)
  File "/usr/lib/python3.5/pyclbr.py", line 144, in _readmodule
    spec = importlib.util._find_spec_from_path(fullmodule, search_path)
  File "/usr/lib/python3.5/importlib/util.py", line 62, in _find_spec_from_path
ValueError: nspkg.__spec__ is None
```

**Comment by hfaran** [comment]
Hi @djbright. Thanks for this report. Since waiting around for someone to fix `pyclbr` is a long shot, I've just gone ahead and replaced its usage in the code with equivalent stuff from `inspect` instead. Here's the PR: https://github.com/hfaran/Tornado-JSON/pull/97

It passes locally so just waiting for CI to go through.

**Can you please check that branch out and test to see if it works for you?** I'm hoping this will work fine but I have only ran tests, and not tested elsewhere so would be useful to get you to test. Thanks.

**Comment by djbright** [comment]
Hi @hfaran! Great! Yep, I will test it out with our project at next opportunity, most likely within a couple of days.
